USE [master]
GO

/****** Object:  Database [ClientsTest]    Script Date: 30/10/2017 09:16:35 a.m. ******/
CREATE DATABASE [ClientsTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClientsTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVEREXPRESS\MSSQL\DATA\ClientsTest.mdf' , SIZE = 500736KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ClientsTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVEREXPRESS\MSSQL\DATA\ClientsTest_log.ldf' , SIZE = 4632576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ClientsTest] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClientsTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ClientsTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ClientsTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ClientsTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ClientsTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ClientsTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [ClientsTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ClientsTest] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ClientsTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ClientsTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ClientsTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ClientsTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ClientsTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ClientsTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ClientsTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ClientsTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ClientsTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ClientsTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ClientsTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ClientsTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ClientsTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ClientsTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ClientsTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ClientsTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ClientsTest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ClientsTest] SET  MULTI_USER 
GO

ALTER DATABASE [ClientsTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ClientsTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ClientsTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ClientsTest] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ClientsTest] SET  READ_WRITE 
GO


