USE [ClientsTest]
GO

/****** Object:  Table [dbo].[CLIENTS]    Script Date: 27/10/2017 09:57:46 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[EMAIL] [nvarchar](50) NULL,
	[DATEOFBIRTH] [date] NOT NULL,
	[TYPEID] [int] NOT NULL,
 CONSTRAINT [PK_CLIENTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CLIENTS]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTS_CLIENT_TYPE] FOREIGN KEY([TYPEID])
REFERENCES [dbo].[CLIENT_TYPE] ([TYPEID])
GO

ALTER TABLE [dbo].[CLIENTS] CHECK CONSTRAINT [FK_CLIENTS_CLIENT_TYPE]
GO


