USE ClientsTest
SET NOCOUNT ON
GO
INSERT INTO CLIENT_TYPE VALUES('NORMAL');
INSERT INTO CLIENT_TYPE VALUES('GOLD');
INSERT INTO CLIENT_TYPE VALUES('PLATINUM');
GO

DECLARE @id int 
DECLARE @fec date 
BEGIN TRAN
	SET @id = 1
	WHILE (@id <= 10000)
	BEGIN
		INSERT INTO CLIENTS(NAME,EMAIL,DATEOFBIRTH,TYPEID) VALUES('CLIENT' + cast(@id as varchar),'CLIENT'+ cast(@id as varchar)+'@gmail.com',DATEADD(DAY, ABS(CHECKSUM(NEWID()) % 3650), '1975-01-01'),cast(RAND()*(4-1)+1 as int))
		SET @id= @id + 1
	END
COMMIT; 

/* UTIL
DELETE CLIENTS
DELETE CLIENT_TYPE
DBCC CHECKIDENT ('CLIENTS', RESEED, 0) 
DBCC CHECKIDENT ('CLIENT_TYPE', RESEED, 0) 
SELECT * FROM CLIENTS order by id
SELECT * FROM CLIENT_TYPE
*/



